# Generated by Django 5.2.7 on 2026-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='womenadd/')),
            ],
        ),
    ]
