# Generated by Django 5.2.7 on 2026-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ladies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ladies',
            name='price',
            field=models.IntegerField(),
        ),
    ]
