# Generated by Django 5.2.7 on 2026-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ladies_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidsname', models.CharField(max_length=100)),
                ('kidsprice', models.IntegerField()),
                ('kidsdescription', models.CharField(max_length=150)),
                ('kidsimage', models.ImageField(upload_to='kidsadd/')),
            ],
        ),
    ]
