# Generated by Django 5.2.7 on 2026-02-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ladies_options_remove_cart_kids_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kids',
            options={'verbose_name': 'Kids', 'verbose_name_plural': 'Kids'},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='kids_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kids'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ladies_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ladies'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
