# Generated by Django 5.2.7 on 2026-02-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_kids_options_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
